### ISSUE TITLE
按教程操作添加代码并更新订阅地址，等几秒后就提示无法切换此配置

### ISSUE THREAD

**Issue by jiaorong2023** [iczrac/Parsers-for-clash#12]
![QQ截图20240323085758](https://github.com/iczrac/Parsers-for-clash/assets/124117556/d6ee88d9-b14c-4183-92b6-681332f66896)
请问这是啥问题呢？

**Comment by iczrac** [comment]
你试试全局之后在用  确保你能跨越长城

**Comment by jiaorong2023** [comment]
已经搞定，先添加预配置，然后再添加订阅就行了，如果在已经订阅的情况下，添加配置，不管怎么刷新还是会报错。
