### ISSUE TITLE
关于避免机场节点无法匹配正则筛选而导致配置出错的解决方法

### ISSUE THREAD

**Issue by cdchs99** [iczrac/Parsers-for-clash#6]
如图，可以在`prepend(append)-proxy-group`对象里手动添加一行`proxies: `
![image](https://github.com/iczrac/Parsers-for-clash/assets/47968720/00e8a9d0-56a2-4b11-98f0-b1b4a9b61c9e)

**Comment by iczrac** [comment]
这个原来就有了啊

**Comment by cdchs99** [comment]
> 这个原来就有了啊

我发现我的方法也不行，没仔细测试，打扰了。后续如果我有想到其他真正的方法，再交流。

**Comment by cdchs99** [comment]
> 这个原来就有了啊

**Comment by cdchs99** [comment]
> 这个原来就有了啊

我刚测试了下，我的方法也不好使。打扰了。下次，如果我有新的方法，再交流。
